### PR TITLE
[Checkbox#866] Fix extanding content issue in stack for single checkbox

### PR DESCRIPTION
**Pull request by aycil-alican**
When you put swiftui single checkbox in stack, It might extend It's content according to parent's frame. It was fixed

### CODE REVIEW

**Comment by LouisBorleeAdevinta** [comment]
Could you add a bit more detail please? like a screenshot or something to further expain the issue

**Comment by aycil-alican** [comment]
There was a issue with swiftui single checkbox in HStack on Polaris side. I faced this issue while I was developing Formfield once time. To solve this issue we were adding fixedSize modifier to checkbox. In this PR I directly put this modifier in single checkbox.
Simulator Screenshot - iPhone 15 Pro - 2024-03-26 at 10 39 01

**Comment by LouisBorleeAdevinta** [comment]
Oh right! I've seen this issue in the Switch component as well I believe, could be worth looking for this in all our components!

**Comment by aycil-alican** [comment]
I have checked accessibility sizes  and It works as expected.

**Review by michael-zimmermann — APPROVED** [review]

**Pull request merged**
